#ifndef SERIALISATION_GLOBAL_H
#define SERIALISATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERIALISATION_LIBRARY)
#  define SERIALISATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERIALISATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#define NS_SERIALISATION ModuleSerialisation
#define NS_STR_SERIALISATION "ModuleSerialisation"

#endif // SERIALISATION_GLOBAL_H
