#ifndef HIGHLEVELCONVENIENCE_GLOBAL_H
#define HIGHLEVELCONVENIENCE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USERINTERFACE_LIBRARY)
#  define USERINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define USERINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif

namespace UserInterface
{
    extern const char* STR_NAMESPACE;
}

#endif // HIGHLEVELCONVENIENCE_GLOBAL_H
